services:
  backend:
    build:
      args:
      - NODE_ENV=development
      context: backend
      target: development
    command: npm run start-watch
    environment:
      - DATABASE_DB=librarysystemssr
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
      - NODE_ENV=development
    ports:
      - 80:80 # Application Port: Standard port where your Express Node.js 
      # application is running inside the Docker container. 
      # This is how users see the output of your code.
      - 9229:9229 # Development Debugger Port: Used for debugging your 
      # application while it's running with Nodemon
      - 9230:9230 # Testing Debugger Port: To debugging your Mocha tests.
    secrets:
      - db-password
    volumes:
      - ./backend:/code
      - back-node-modules:/code/node_modules 
    networks:
      - public
      - private
    depends_on:
      db:
        condition: service_healthy 
  db:
    image: mysql:8.4.6
    platform: linux/amd64
    command: --mysql-native-password=ON
    restart: always
    ports:
      - 3307:3306
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - private
    environment:
      - LANG=C.UTF-8 # CRIT: Causes the mysql client to assume the utf8 
      # encoding. Due to Cyrillic chars or special chars are being changed to
      # special non sense characters at init, using docker-compose.
      - MYSQL_DATABASE=librarysystemssr
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=$MYSQL_ROOT_PASSWORD_FILE"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s
networks:
  public:
  private:
volumes:
  back-node-modules:
  db-data:
secrets:
  db-password:
    file: db/password.txt
